# Stores MOGA constants
LENGTH_OF_BIT_STRING = 32
POPULATION_SIZE = 10
MUTATION_DISTRIBUTION_INDEX = 20  # Should be between 20-100
MUTATION_INDEX = 20
N = 2
NUMBER_OF_ITERATIONS = 100
MUTATION_PROBABILITY = 0.1